name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'app/container/**'

defaults:
  run:
    working-directory: app/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_SECRET_ACCESS_KEY }}

      - name: Deply To OSS
        run: ossutil cp -rf test.txt oss://bucket/path

